// <auto-generated />
namespace amigopet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_petcontrollers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_petcontrollers));
        
        string IMigrationMetadata.Id
        {
            get { return "202102190305411_add_petcontrollers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
